### ISSUE TITLE
Incompatable WITH dtbo.img  ?

### ISSUE THREAD

**Issue by Lg-PWNd** [cfig/Android_boot_image_editor#106]
So i'm trying to de-compile the dtbo_a and i've pulled it to pc.. adb root && adb pull /dev/block/bootdevice/by-name/dtbo_a dtbo.img

then i tried ./gradlew unpack dtbo.img
i got this
Android_boot_image_editor$ ./gradlew unpack dtbo.img

FAILURE: Build failed with an exception.

* What went wrong:
Task 'dtbo.img' not found in root project 'boot'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6s
######################################################

then i tried renaming dtbo.img to boot.img and did this...$ ./gradlew unpack

and 
$ ./gradlew unpack

> Task :unpack FAILED
15:44:35.682 [main] WARN  cfig.packable.PackableLauncher - [boot.img] will be handled by [BootImgParser]
15:44:35.862 [main] WARN  cfig.packable.PackableLauncher - 'unpack' sequence initialized
15:44:35.871 [main] INFO  Helper - deleting uiderrors
15:44:35.887 [main] INFO  cfig.packable.BootImgParser - header version 0
15:44:36.188 [main] WARN  cfig.bootimg.v2.BootHeaderV2 - BootImgHeader constructor
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:108)
Caused by: java.lang.IllegalArgumentException: stream doesn't look like Android Boot Image Header
        at cfig.bootimg.v2.BootHeaderV2.<init>(BootHeaderV2.kt:64)
        at cfig.bootimg.v2.BootV2$Companion.parse(BootV2.kt:87)
        at cfig.packable.BootImgParser.unpack(BootImgParser.kt:45)
        ... 8 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unpack'.
> Process 'command '/usr/lib/jvm/zulu-17-amd64/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
10 actionable tasks: 1 executed, 9 up-to-date
#############################################################

so can anyone tell me whats going wrong here? maybe i'm not clear on how to use this for dtbo.img's
thanks for any help

**Comment by cfig** [comment]
Hi @astrayal ,
Just try the command
```
./gradlew unpack
```
The tool will use "dtbo.img" if it's present in current directory.

**Comment by astrayal** [comment]
Thanks

**Comment by cfig** [comment]
So is the problem solved?
