### ISSUE TITLE
Unpack payload.bin failed 

### ISSUE THREAD

**Issue by 5n0wfish** [cfig/Android_boot_image_editor#108]
When I unpack `xiaomi 13pro` [rom](https://xiaomirom.com/download/xiaomi-13-pro-nuwa-stable-V14.0.4.0.TMBCNXM/#china-recovery)->payload.bin, it got an error.
```
14:03:53.706 [main] INFO  cc.cfig.droid.ota.Payload - Creating build/payload/
14:03:53.863 [main] INFO  cc.cfig.droid.ota.Payload -   header  info dumped to build/payload/header.json
14:03:53.883 [main] INFO  cc.cfig.droid.ota.Payload -  manifest info dumped to build/payload/manifest.json
14:03:53.888 [main] INFO  cc.cfig.droid.ota.Payload - signature info dumped to build/payload/signatures.txt
14:03:53.891 [main] INFO  cc.cfig.droid.ota.Payload - There are 36 partitions [abl, aop, aop_config, bluetooth, boot, cpucp, devcfg, dsp, dtbo, featenabler, hyp, imagefv, init_boot, keymaster, modem, multiimgqti, odm, product, qupfw, recovery, shrm, system, system_dlkm, system_ext, tz, uefi, uefisecapp, vbmeta, vbmeta_system, vendor, vendor_boot, vendor_dlkm, xbl, xbl_config, xbl_ramdump, mi_ext]
14:03:53.891 [main] INFO  cc.cfig.droid.ota.Payload - dumping images to build/payload/
14:03:53.891 [main] INFO  cc.cfig.droid.ota.Payload - [ 1/36] extracting           abl.img (1 ops)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:108)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: -1073741515 (Exit value: -1073741515)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
        at cc.cfig.droid.ota.Payload.decompress(Payload.kt:187)
        at cc.cfig.droid.ota.Payload.unpackInternal(Payload.kt:205)
        at cc.cfig.droid.ota.Payload.unpack(Payload.kt:229)
        at cfig.packable.PayloadBinParser.unpack(PayloadBinParser.kt:32)
        ... 8 more
```

**Comment by cfig** [comment]
Are you using "miui_NUWA_V14.0.4.0.TMBCNXM_c5625d2228_13.0.zip" 
md5 payload.bin:
```
545d2eeebc74c1558f5df884ebfdfd6e  payload.bin
```
unpack works fine on my side. Are we using the same file?

**Comment by cfig** [comment]
Hi @5n0wfish ,
First please check java version: `java -version`, java 17 is required.

Then I tried on linux & windows
1. Linux works fine.
2. Windows
* under Git Bash
works fine. "Git Bash" if there if you install git windows version.
* under Anaconda Power Shell Prompt
failed due to missing of program "xzcat".

Do you have "git bash"? Can you have a try?

**Comment by 5n0wfish** [comment]
Thanks.

It works fine on git bash, and windows pwershell dont have `xzcat` command
