### ISSUE TITLE
why i cant pack system

### ISSUE THREAD

**Issue by slwyts** [cfig/Android_boot_image_editor#112]
i only edit any files
`
> Task :pack FAILED
13:33:37.898 [main] WARN  cfig.packable.PackableLauncher - [system.img] will be handled by [SparseImgParser]
13:33:38.018 [main] WARN  cfig.packable.PackableLauncher - 'pack' sequence initialized
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:108)
Caused by: kotlin.NotImplementedError: An operation is not implemented: not implemented
        at cfig.utils.SparseImgParser.pack(SparseImgParser.kt:94)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 5 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pack'.
> Process 'command '/usr/lib/jvm/java-19-openjdk/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
25 actionable tasks: 3 executed, 22 up-to-date
`

**Comment by cfig** [comment]
Hi @slwyts,
Packing system.img is not supported yet.

**Comment by slwyts** [comment]
When can it be realized? Or you switch to ext4 to mount the image, and sign after modification

**Comment by cfig** [comment]
It will be done with low priority. 
"Or you switch to ext4 to mount the image, and sign after modification" => I've been thinking about this solution too. Needs some tests.

**Comment by cfig** [comment]
A new commit has been submitted to support sparsed ext4 (or raw ext4) images.
https://github.com/cfig/Android_boot_image_editor/issues/133

I tested with vendor_dlkm.img, this should also work for other ext4 based images.

**Comment by cfig** [comment]
Special note: it only works for dynamic partitioned system.img., and vbmeta.img should also be updated together.
