### ISSUE TITLE
If you have time, fix the ramdisk without a kernel. Huawei ramdisk.img

### ISSUE THREAD

**Issue by xxroot** [cfig/Android_boot_image_editor#122]
If you have time, fix the ramdisk without a kernel. Huawei ramdisk.img

'Caused by: java.io.FileNotFoundException: build/unzip_boot/kernel (没有那个文件或目录)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at cfig.bootimg.Common$Companion.hashFileAndSize(Common.kt:210)
        at cfig.bootimg.v2.BootV2.pack(BootV2.kt:397)
        at cfig.packable.BootImgParser.pack(BootImgParser.kt:86)
        ... 8 more
'
[ramdisk.zip](https://github.com/cfig/Android_boot_image_editor/files/11632490/ramdisk.zip)

**Comment by cfig** [comment]
Never seen such ramdisk.img for /ramdisk partition.
What's the Huawei device model ? I see "androidboot.hardware=qcom"

**Comment by xxroot** [comment]
honour 30 list&nbsp;


智酷网
***@***.***



&nbsp;

**Comment by xxroot** [comment]
honour 30 lite

**Comment by xxroot** [comment]
In my opinion, this problem is solved by adding a judgment when packing the kernel. If the kernel does not exist, skip the kernel packing

**Comment by cfig** [comment]
> In my opinion, this problem is solved by adding a judgment when packing the kernel. If the kernel does not exist, skip the kernel packing

Yes, that's the idea. I quickly checked several Huawei & Honor phones, they all have "ramdisk" or "ramdisk_a/b" partitions.

**Comment by xxroot** [comment]
Caused by: java.lang.IllegalStateException: This should not happen, please add comments at: https://github.com/cfig/Android_boot_image_editor/issues/122

**Comment by cfig** [comment]
Please rename the file to "ramdisk.img"

**Comment by cfig** [comment]
Nice
