### ISSUE TITLE
Pack recovery.img failed.

### ISSUE THREAD

**Issue by VMTask** [cfig/Android_boot_image_editor#139]
I want to unpack and pack a recovery.img,
At first, the program worked normally.
And I want to pack the recovery.img,it results this error:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:120)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 9009 (Exit value: 9009)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
        at cfig.bootimg.v2.BootV2.pack(BootV2.kt:524)
        at cfig.packable.BootImgParser.pack(BootImgParser.kt:88)
        ... 8 more
```

**Comment by cfig** [comment]
can you upload the recovery.img you used?
