### ISSUE TITLE
Not able to repack recovery.img

### ISSUE THREAD

**Issue by Lelonio** [cfig/Android_boot_image_editor#152]
OnePlus 8T here, recovery is TWRP.

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:144)
Caused by: java.lang.IllegalArgumentException: invalid os_version
	at cfig.bootimg.Common$Companion.packOsVersion(Common.kt:75)
	at cfig.bootimg.v2.BootHeaderV2.encode(BootHeaderV2.kt:125)
	at cfig.bootimg.v2.BootV2.pack(BootV2.kt:486)
	at cfig.packable.BootImgParser.packInternal(BootImgParser.kt:121)
	at cfig.packable.BootImgParser.pack(BootImgParser.kt:143)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 5 more

**Comment by cfig** [comment]
Can you attach the twrp recovery image here?

**Comment by cfig** [comment]
Close legacy issue
