### ISSUE TITLE
Error unpack dtbo.img: where is external/mkdtboimg.py ?

### ISSUE THREAD

**Issue by sceext2** [cfig/Android_boot_image_editor#42]
Command and output:

```
> ./gradlew unpack

> Task :unpack FAILED
[main] WARN cfig.packable.PackableLauncher - [dtbo.img] will be handled by [DtboParser]
[main] WARN cfig.packable.PackableLauncher - 'unpack' sequence initialized
[main] INFO cfig.packable.DtboParser - [external/mkdtboimg.py, dump, dtbo.img, --dtb, build/unzip_boot/dtb, --output, build/unzip_boot/dtbo.header]
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:92)
Caused by: java.io.IOException: Cannot run program "external/mkdtboimg.py" (in directory "."): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:621)
        at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
        at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
        at cfig.packable.DtboParser.execInDirectory(DtboParser.kt:76)
        at cfig.packable.DtboParser.unpack(DtboParser.kt:36)
        ... 8 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 16 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unpack'.
> Process 'command '/usr/lib/jvm/java-8-openjdk/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
17 actionable tasks: 1 executed, 16 up-to-date
>
```

Using this version:  

```
> git log
commit 125418c99de218b17855fb69733c0b6a986c6a7f (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: cfig <yuyezhong@gmail.com>
Date:   Tue Jun 23 11:08:43 2020 +0800

    Squashed commit of the following:
```

Where to get this tool ?  `external/mkdtboimg.py`

Thank you.

**Comment by cfig** [comment]
Hi,
Please fetch latest code, the fix is submitted as:

https://github.com/cfig/Android_boot_image_editor/commit/4bce4a0f394e4d94c4dfa3589ac1a611f81535b7

**Comment by sceext2** [comment]
Thank you.
