### ISSUE TITLE
exception happened when decompile google aosp boot img

### ISSUE THREAD

**Issue by 99degree** [cfig/Android_boot_image_editor#43]
> Task :unpack FAILED
[main] WARN cfig.packable.PackableLauncher - [boot.img] will be handled by [BootImgParser]
[main] WARN cfig.packable.PackableLauncher - 'unpack' sequence initialized
[main] INFO cfig.packable.BootImgParser - header version 3
[main] WARN cfig.bootimg.v3.BootHeaderV3 - BootImgHeaderV3 constructor
[main] INFO KernelExtractor - [aosp/build/tools/extract_kernel.py, --input, build/unzip_boot/kernel, --output-configs, build/unzip_boot/kernel_configs.txt, --output-version, build/unzip_boot/kernel_version.txt]
[main] INFO KernelExtractor - kernel version: [5.9.0]
[main] INFO KernelExtractor - kernel config dumped to : build/unzip_boot/kernel_configs.txt
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:92)
Caused by: java.util.zip.ZipException: Not in GZIP format
        at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:166)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:80)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:92)
        at cfig.Helper$Companion.unGnuzipFile(Helper.kt:116)
        at cfig.bootimg.Common$Companion.dumpRamdisk(Common.kt:113)
        at cfig.bootimg.v3.BootV3.extractImages(BootV3.kt:150)
        at cfig.packable.BootImgParser.unpack(BootImgParser.kt:33)
        ... 8 more

**Comment by 99degree** [comment]
[boot-mainline.zip](https://github.com/cfig/Android_boot_image_editor/files/5354753/boot-mainline.zip)

**Comment by cfig** [comment]
Thanks for issue reporting. 
Seems the ramdisk part is packed in LZ4. I will see if we can support it quickly.

**Comment by cfig** [comment]
LZ4 support has been added to "dev" branch, but I don't have a chance to verify the images on a real device.
unpack/pack works fine.

**Comment by 99degree** [comment]
sorry and i dont have any device to test too.
