### ISSUE TITLE
unknown issue caused fail on pack

### ISSUE THREAD

**Issue by 99degree** [cfig/Android_boot_image_editor#44]
unpack is success, but pack fail.

> Task :pack FAILED
[main] WARN cfig.packable.PackableLauncher - [boot.img] will be handled by [BootImgParser]
[main] WARN cfig.packable.PackableLauncher - 'pack' sequence initialized
[main] INFO cfig.packable.BootImgParser - Loading config from build/unzip_boot/boot.json
[main] INFO cfig.bootimg.Common - Deleting build/unzip_boot/ramdisk.img.gz ...
[main] INFO cfig.bootimg.Common - Deleting build/unzip_boot/ramdisk.img ...
[main] INFO cfig.bootimg.v2.BootV2 - OS Major: 16
[main] INFO cfig.bootimg.Common - Packing rootfs build/unzip_boot//root ...
[main] INFO cfig.bootimg.Common - CMD: aosp/mkbootfs.16/build/exe/mkbootfs/mkbootfs build/unzip_boot//root -> PIPE -> build/unzip_boot/ramdisk.img.gz
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:92)
Caused by: java.io.IOException: Cannot run program "aosp/mkbootfs.16/build/exe/mkbootfs/mkbootfs" (in directory "."): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at java.base/java.lang.Runtime.exec(Runtime.java:592)
        at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
        at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
        at cfig.bootimg.Common$Companion.packRootfs(Common.kt:186)
        at cfig.bootimg.v2.BootV2.pack(BootV2.kt:329)
        at cfig.packable.BootImgParser.pack(BootImgParser.kt:62)
        ... 8 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 18 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pack'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
20 actionable tasks: 3 executed, 17 up-to-date

**Comment by 99degree** [comment]
root@LAPTOP:~/source/Android_boot_image_editor# find -name mkbootfs
./aosp/mkbootfs.10/src/mkbootfs
./aosp/mkbootfs.10/build/objs/mkbootfs
./aosp/mkbootfs.10/build/exe/mkbootfs
./aosp/mkbootfs.10/build/exe/mkbootfs/mkbootfs
./aosp/mkbootfs.11/src/mkbootfs
./aosp/mkbootfs.11/build/objs/mkbootfs
./aosp/mkbootfs.11/build/exe/mkbootfs
./aosp/mkbootfs.11/build/exe/mkbootfs/mkbootfs
root@LAPTOP-VDEV89N4:~/source/Android_boot_image_editor#

**Comment by cfig** [comment]
I see
`[main] INFO cfig.bootimg.v2.BootV2 - OS Major: 16`
Can attach your boot.img here?

If it's confidential, you can simply fix the error by modify
bbootimg/src/main/kotlin/bootimg/v2/BootV2.kt
```
diff --git a/bbootimg/src/main/kotlin/bootimg/v2/BootV2.kt b/bbootimg/src/main/kotlin/bootimg/v2/BootV2.kt
index 8ba8814..78c5ad6 100644
--- a/bbootimg/src/main/kotlin/bootimg/v2/BootV2.kt
+++ b/bbootimg/src/main/kotlin/bootimg/v2/BootV2.kt
@@ -334,7 +334,7 @@ data class BootV2(
             } else {
                 File(this.ramdisk.file!!).deleleIfExists()
                 File(this.ramdisk.file!!.removeSuffix(".gz")).deleleIfExists()
-                Common.packRootfs("${workDir}/root", this.ramdisk.file!!, parseOsMajor())
+                Common.packRootfs("${workDir}/root", this.ramdisk.file!!, 11)
             }
             this.ramdisk.size = File(this.ramdisk.file!!).length().toInt()
         }

```

**Comment by 99degree** [comment]
Thx for reply. The boot img is not secret, just an AOSP/modified rom form either xda or Lineageos which i can't remember. and I did not it kept with a local copy too. Once I i can found it will update it here. Thx again for that.

**Comment by 99degree** [comment]
Ah, I found it once again but figured it out not a AOSP/xda but a twrp from below:

www.twrp.me 

TWRP for mermaid

dorect link:
https://dl.twrp.me/mermaid/twrp-3.4.0-1-mermaid.img.html

**Comment by cfig** [comment]
Unbelievable, the image says its OS version is 16.
```
    "osVersion" : "16.1.0",
    "osPatchLevel" : "2025-12-00",
```
I can modify the code a little bit to accommodate such unusual images.
Anyway, I loved twrp before ....

**Comment by cfig** [comment]
Please sync the code, it's now able to pack the bigger os versions now.
