### ISSUE TITLE
vbmeta pack FAILED

### ISSUE THREAD

**Issue by sanshu-rom** [cfig/Android_boot_image_editor#47]
./gradlew pack

> Task :pack FAILED
[main] WARN cfig.packable.PackableLauncher - [vbmeta_a.img] will be handled by [VBMetaParser]
[main] WARN cfig.packable.PackableLauncher - 'pack' sequence initialized
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:92)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "flags-pVg5ArA" (class avb.desc.KernelCmdlineDescriptor), not marked as ignorable (7 known properties: "sequence", "num_bytes_following", "tag", "cmdline", "flagsInterpretation", "cmdlineLength-WZ4Q5Ns", "flags-WZ4Q5Ns"])
 at [Source: (File); line: 238, column: 26] (through reference chain: avb.AVBInfo["auxBlob"]->avb.blob.AuxBlob["kernelCmdlineDescriptor"]->java.util.ArrayList[0]->avb.desc.KernelCmdlineDescriptor["flags-pVg5ArA"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1582)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:291)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:250)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3331)
        at cfig.Avb.packVbMeta(Avb.kt:273)
        at cfig.Avb.packVbMetaWithPadding(Avb.kt:309)
        at cfig.Avb.packVbMetaWithPadding$default(Avb.kt:308)
        at cfig.packable.VBMetaParser.pack(VBMetaParser.kt:26)
        ... 8 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pack'.
> Process 'command '/usr/lib/jvm/java-8-openjdk/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
20 actionable tasks: 3 executed, 17 up-to-date

**Comment by cfig** [comment]
Hi,
Are you using an intermediate version?
` "flags-pVg5ArA" ` error is only observed when I bump kotlin version.
Please try latest origin/master,  it should work.
Thanks.

**Comment by sanshu-rom** [comment]
Modify "flags-pVg5ArA" to "flags-WZ4Q5Ns"

**Comment by cfig** [comment]
Can you attach your vbmeta.img here?

**Comment by sanshu-rom** [comment]
[vbmeta.zip](https://github.com/cfig/Android_boot_image_editor/files/5606473/vbmeta.zip)

**Comment by cfig** [comment]
@sanshu-rom , 
Should be fixed by
https://github.com/cfig/Android_boot_image_editor/commit/9e30b56015d46422be0de5e1d1a1c9d3e72398e8
KernelCmdlineDescriptor is not used in latest AOSP code by default. I will add this into integration test case.

Can you fetch code and try again?

**Comment by sanshu-rom** [comment]
Problem solving

` ./gradlew pack

> Task :pack
[main] WARN cfig.packable.PackableLauncher - [vbmeta_a.img] will be handled by [VBMetaParser]
[main] WARN cfig.packable.PackableLauncher - 'pack' sequence initialized
[main] INFO avb.blob.AuxBlob - encodePubKey(): size = 1032, algorithm key size: 1032
[main] INFO avb.blob.AuxBlob - Using the same key as original vbmeta
[main] INFO avb.blob.AuxBlob - no pubkey metadata in auxBlob
[main] INFO avb.blob.AuxBlob - encodePubKey(): size = 1032, algorithm key size: 1032
[main] INFO cfig.Avb - pkmd size: 0, pkmd offset : 4072
[main] INFO cfig.Avb - raw vbmeta size 4928, padding size 3264, total blob size 8192
[main] INFO cfig.Avb - Writing padded vbmeta to file: vbmeta_a.img.signed
[main] WARN cfig.packable.PackableLauncher - 'pack' sequence completed

BUILD SUCCESSFUL in 19s
20 actionable tasks: 3 executed, 17 up-to-date`

**Comment by cfig** [comment]
Good to hear.
