### ISSUE TITLE
Windows解包问题

### ISSUE THREAD

**Issue by scarlet-glass** [cfig/Android_boot_image_editor#58]
我clone源代码后，在Windows PowerShell下解包boot.img，遇到如下错误。

`PS E:\linux\boot_editor_r11> .\gradlew.bat pack
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :pack
14:53:03:965 WARN PackableLauncher - [boot.img] will be handled by [BootImgParser]
14:53:04:315 WARN PackableLauncher - 'pack' sequence initialized
14:53:04:319 INFO BootImgParser - Loading config from build/unzip_boot/boot.json
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:92)
Caused by: java.io.FileNotFoundException: build\unzip_boot\boot.json (系统找不到指定的路径。)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1029)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3413)
        at cfig.packable.BootImgParser.pack(BootImgParser.kt:55)
        ... 8 more

> Task :pack FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pack'.
> Process 'command 'C:\Program Files\Java\jdk-11.0.10\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 50s
11 actionable tasks: 3 executed, 8 up-to-date
PS E:\linux\boot_editor_r11>`

我使用你封装的那个R11包就不会有这个问题。是在线编译的东西出错了吗？

**Comment by cfig** [comment]
release的那个版本，是不需要编译的，另外
release的那个版本，是不需要编译的，另外那些脚本设置了一些可执行程序的路径什么的，在source code版本里可能没有设置完整吧。

最近太忙了，明天抽空看一下哈。那些脚本设置了一些可执行程序的路径什么的，在source code版本里可能没有设置完整吧。

最近太忙了，明天抽空看一下哈。

**Comment by cfig** [comment]
试了一把，没问题的啊。
Windows上的auto test也过了。是不是忘了先unpack一把？

**Comment by cfig** [comment]
怎样？搞定没有？

**Comment by scarlet-glass** [comment]
搞定了，原来是我的命令用错了，我调用成了gradlew.bat
