### ISSUE TITLE
how to fix pack boot V3

### ISSUE THREAD

**Issue by Leminh8686** [cfig/Android_boot_image_editor#59]
pls help me pack boot.img.v3 (android11)

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:92)
Caused by: java.nio.BufferOverflowException
        at java.base/java.nio.HeapByteBuffer.put(HeapByteBuffer.java:221)
        at cfig.bootimg.Common$Companion.writePaddedFile(Common.kt:287)
        at cfig.bootimg.v3.BootV3.pack(BootV3.kt:104)
        at cfig.packable.BootImgParser.pack(BootImgParser.kt:57)
        ... 8 more

**Comment by cfig** [comment]
Have you tried latest code from 'master' branch?
Suppose master branch should have fixed the problem.
If not, please attach your boot.img here, and I can have a try.

Thanks~

**Comment by Leminh8686** [comment]
Here sir https://drive.google.com/file/d/1os3cuULGo-36QUyibc8kMTKzgcqCLIOz/view?usp=drivesdk

I can unpack but can't not repack

**Comment by cfig** [comment]
Can you have a try with latest 'rc' branch?
```
git fetch origin
git checkout origin/rc
```
and then do unpack and pack.

**Comment by Leminh8686** [comment]
> Can you have a try with latest 'rc' branch?
> 
> ```
> git fetch origin
> git checkout origin/rc
> ```
> 
> and then do unpack and pack.

Yes latest bro.
I use on windowns and linux

**Comment by cfig** [comment]
does it work?

**Comment by cfig** [comment]
Fixed and added into integration test case.
