### ISSUE TITLE
Windows 的Linux子系统解包dtbo问题

### ISSUE THREAD

**Issue by scarlet-glass** [cfig/Android_boot_image_editor#60]
我使用Windows的Linux子系统解包dtbo.img时，报以下错误是因为python的版本太高了，改用python 2.7.18即可正常解包了。
我创建了拉取请求，如有必要你可以合入：https://github.com/scarlet-glass/Android_boot_image_editor/tree/patch-1

**log：**
`scarlet-glass@DESKTOP-VK785N8:~/Android_boot_image_editor$ ./gradlew unpack

> Task :unpack FAILED
17:20:58:185 WARN PackableLauncher - [dtbo.img] will be handled by [DtboParser]
17:20:58:251 WARN PackableLauncher - 'unpack' sequence initialized
17:20:58:255 INFO DtboParser - [aosp/system/libufdt/utils/src/mkdtboimg.py, dump, dtbo.img, --dtb, build/unzip_boot/dtb, --output, build/unzip_boot/dtbo.header]
/usr/bin/env: “python”: 没有那个文件或目录
17:20:58:288 ERROR DtboParser - can not exec command
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:92)
Caused by: java.io.FileNotFoundException: build/unzip_boot/dtbo.header (没有那个文件或目录)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at cfig.packable.DtboParser.unpack(DtboParser.kt:43)
        ... 8 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unpack'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
20 actionable tasks: 1 executed, 19 up-to-date`

**Comment by cfig** [comment]
Merged.
I will update scripts later to run on py3.

**Comment by cfig** [comment]
https://github.com/cfig/Android_boot_image_editor/commit/9d2a7a14c2ef424075b1a9f776e4998309446fbf

**Comment by scarlet-glass** [comment]
nice
