### ISSUE TITLE
fail to unpack xiaomi redmi note 9 pro joyeuse recovery img, and boot.img is for reference.

### ISSUE THREAD

**Issue by 99degree** [cfig/Android_boot_image_editor#61]
04:18:52:690 WARN PackableLauncher - [boot.img] will be handled by [BootImgParser]
04:18:52:774 WARN PackableLauncher - 'unpack' sequence initialized
04:18:52:782 INFO BootImgParser - header version 2
04:18:52:793 WARN BootHeaderV2 - BootImgHeader constructor
04:18:52:797 INFO Avb - python aosp/avb/avbtool.v1.2.py verify_image --image boot.img
sha256 digest of recovery.img does not match digest in descriptor
aosp/avb/avbtool.v1.2.py: Error verifying descriptor.
Verifying image boot.img using embedded public key
vbmeta: Successfully verified footer and SHA256_RSA2048 vbmeta struct in boot.img
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:106)
Caused by: java.lang.IllegalArgumentException: boot.img failed integrity check by "python aosp/avb/avbtool.v1.2.py verify_image --image boot.img"
        at cfig.Avb$Companion.verifyAVBIntegrity(Avb.kt:474)
        at cfig.bootimg.v2.BootV2$Companion.parse(BootV2.kt:98)
        at cfig.packable.BootImgParser.unpack(BootImgParser.kt:45)
        ... 8 more

FAILURE: Build failed with an exception.

https://www.mediafire.com/file/xkg9srlaxe0s7bi/recovery.zip/file
[boot.zip](https://github.com/cfig/Android_boot_image_editor/files/6556633/boot.zip)

**Comment by 99degree** [comment]
looks like the reovery.img is rebuild after first bootup into miui. so neglete this file.
