### ISSUE TITLE
lineageos official recovery img cant unpack

### ISSUE THREAD

**Issue by 99degree** [cfig/Android_boot_image_editor#62]
The img like is at bottom.

log:
> Task :unpack FAILED
23:32:01:945 WARN PackableLauncher - [boot.img] will be handled by [BootImgParser]
23:32:02:041 WARN PackableLauncher - 'unpack' sequence initialized
23:32:02:045 INFO BootImgParser - header version 1
23:32:02:057 WARN BootHeaderV2 - BootImgHeader constructor
23:32:02:061 INFO Avb - python aosp/avb/avbtool.v1.2.py verify_image --image boot.img
sha256 digest of recovery.img does not match digest in descriptor
aosp/avb/avbtool.v1.2.py: Error verifying descriptor.
Verifying image boot.img using embedded public key
vbmeta: Successfully verified footer and NONE vbmeta struct in boot.img
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:106)
Caused by: java.lang.IllegalArgumentException: boot.img failed integrity check by "python aosp/avb/avbtool.v1.2.py verify_image --image boot.img"
        at cfig.Avb$Companion.verifyAVBIntegrity(Avb.kt:474)
        at cfig.bootimg.v2.BootV2$Companion.parse(BootV2.kt:98)
        at cfig.packable.BootImgParser.unpack(BootImgParser.kt:45)
        ... 8 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unpack'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
20 actionable tasks: 1 executed, 19 up-to-date
root@LAPTOP-VDEV89N4:~/source/Android_boot_image_editor# cp /mnt/c/d_drive/aosp/lineage-17.1-20210526-recovery-davinci.img  boot.img
root@LAPTOP-VDEV89N4:~/source/Android_boot_image_editor# ./gradlew unpack

> Task :unpack FAILED
23:32:27:693 WARN PackableLauncher - [boot.img] will be handled by [BootImgParser]
23:32:27:786 WARN PackableLauncher - 'unpack' sequence initialized
23:32:27:793 INFO BootImgParser - header version 1
23:32:27:805 WARN BootHeaderV2 - BootImgHeader constructor
23:32:27:810 INFO Avb - python aosp/avb/avbtool.v1.2.py verify_image --image boot.img
sha256 digest of recovery.img does not match digest in descriptor
aosp/avb/avbtool.v1.2.py: Error verifying descriptor.
Verifying image boot.img using embedded public key
vbmeta: Successfully verified footer and NONE vbmeta struct in boot.img
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:106)
Caused by: java.lang.IllegalArgumentException: boot.img failed integrity check by "python aosp/avb/avbtool.v1.2.py verify_image --image boot.img"
        at cfig.Avb$Companion.verifyAVBIntegrity(Avb.kt:474)
        at cfig.bootimg.v2.BootV2$Companion.parse(BootV2.kt:98)
        at cfig.packable.BootImgParser.unpack(BootImgParser.kt:45)
        ... 8 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unpack'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

https://mirrorbits.lineageos.org/recovery/davinci/20210526/lineage-17.1-20210526-recovery-davinci.img

**Comment by cfig** [comment]
change
`cp /mnt/c/d_drive/aosp/lineage-17.1-20210526-recovery-davinci.img boot.img`
to ->
`cp /mnt/c/d_drive/aosp/lineage-17.1-20210526-recovery-davinci.img recovery.img`
should fix the error.

Can you have a try?

**Comment by 99degree** [comment]
yes it does ok. thx for reply. so any possibly merge boot and recovery procedure altogether maybe?

**Comment by cfig** [comment]
Latest code in "master" branch will ignore avb verify errors. :)
