### ISSUE TITLE
打包dtbo.img报错

### ISSUE THREAD

**Issue by scarlet-glass** [cfig/Android_boot_image_editor#71]
scarlet-glass@scarlet-glass-PC:~/Android_boot_image_editor-master$ ./gradlew pack

> Task :pack FAILED
09:08:36:540 WARN PackableLauncher - [dtbo.img] will be handled by [DtboParser]
09:08:36:616 WARN PackableLauncher - 'pack' sequence initialized
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:105)
Caused by: java.io.FileNotFoundException: build/unzip_boot/dtbo.header (没有那个文件或目录)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at cfig.packable.DtboParser.pack(DtboParser.kt:79)
        ... 8 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pack'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
23 actionable tasks: 3 executed, 20 up-to-date
scarlet-glass@scarlet-glass-PC:~/Android_boot_image_editor-master$

**Comment by cfig** [comment]
把用的dtbo.img附件传上来？
本地用pixel的dtbo测试是好的。

**Comment by scarlet-glass** [comment]
链接：https://pan.baidu.com/s/1eI-gaq5ttkNFktnqwQMBNQ 
提取码：nizp

**Comment by cfig** [comment]
unpack:
* Windows：由于没有Windows版本的dtc工具，dtbo解不了。
* 在Linux下测试(Debian 11, x86_64)，正常.
* 在WSL Debian里测试： 碰到dtc工具错误。
```
dtc: livetree.c:565: get_node_by_phandle: Assertion `generate_fixups' failed.
```

pack:
目前功能不支持。

对dtb/dts不熟悉，dtc工具用的也不溜。sorry for that。。。

**Comment by cfig** [comment]
It passed local tests. Kindly have another try :)

**Comment by scarlet-glass** [comment]
好久不玩这个了，哈哈

**Comment by cfig** [comment]
苦逼码农向你投来羡慕的目光
