### ISSUE TITLE
Failed to Unpack Oculus Go Image

### ISSUE THREAD

**Issue by moocow1452** [cfig/Android_boot_image_editor#76]
Using the unlocked_build.zip available at https://developer.oculus.com/blog/unlocking-oculus-go/ , I was not able to proceed past the unpacking step. Here's my output:

https://paste.debian.net/1218100

I'm using WSL2 Ubuntu if that changes anything.

**Comment by cfig** [comment]
```
> Task :unpack
14:44:40:360 WARN PackableLauncher - [boot.img] will be handled by [BootImgParser]
14:44:41:524 WARN PackableLauncher - 'unpack' sequence initialized
14:44:41:612 INFO BootImgParser - header version 13303406
14:44:45:595 WARN BootHeaderV3 - BootImgHeaderV3/V4 constructor
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:105)
Caused by: java.lang.IllegalArgumentException: stream doesn't look like Android Boot Image V3 Header
        at cfig.bootimg.v3.BootHeaderV3.<init>(BootHeaderV3.kt:41)
        at cfig.bootimg.v3.BootV3$Companion.parse(BootV3.kt:53)
        at cfig.packable.BootImgParser.unpack(BootImgParser.kt:49)
        ... 8 more

> Task :unpack FAILED

FAILURE: Build failed with an exception.

```

**Comment by cfig** [comment]
Hi @moocow1452 ,
The file `Oculus_Go_SW_Unlock_v1/unlocked_build.zip` is OTA package, `boot.img` is packed inside `payload.bin`.
After extracting boot image from it, I can unpack the image.

```
                        Unpack Summary of boot.img
┌───────────────────────────────────────┬──────────────────────────────────────┐
│What                                   │Where                                 │
└───────────────────────────────────────┴──────────────────────────────────────┘
┌───────────────────────────────────────┬──────────────────────────────────────┐
│image info                             │build/unzip_boot/boot.json            │
├───────────────────────────────────────┼──────────────────────────────────────┤
│kernel                                 │build/unzip_boot/kernel               │
│\-- version [3.18.31]                  │build/unzip_boot/kernel_version.txt   │
│\-- config                             │build/unzip_boot/kernel_configs.txt   │
├───────────────────────────────────────┼──────────────────────────────────────┤
│ramdisk                                │build/unzip_boot/ramdisk.img.gz       │
│\-- extracted ramdisk rootfs           │build/unzip_boot/root                 │
└───────────────────────────────────────┴──────────────────────────────────────┘


```

**Comment by cfig** [comment]
[boot.img.gz](https://github.com/cfig/Android_boot_image_editor/files/7473859/boot.img.gz)

**Comment by cfig** [comment]
Please raise your hand if you still meet any problems in the above steps.
