### ISSUE TITLE
repack twrp android 12 error

### ISSUE THREAD

**Issue by bgman111111** [cfig/Android_boot_image_editor#99]
```
> Task :pack
22:28:05.271 [main] WARN  cfig.packable.PackableLauncher - [recovery.img] will be handled by [BootImgParser]
22:28:05.320 [main] WARN  cfig.packable.PackableLauncher - 'pack' sequence initialized
22:28:05.326 [main] INFO  cfig.packable.BootImgParser - Loading config from build/unzip_boot/recovery.json
22:28:05.434 [main] INFO  cfig.bootimg.Common - Deleting build/unzip_boot/ramdisk.img.gz ...
22:28:05.437 [main] INFO  cfig.bootimg.Common - Deleting build/unzip_boot/ramdisk.img ...
22:28:05.443 [main] INFO  cfig.bootimg.Common - Packing rootfs build/unzip_boot/root ...
22:28:05.454 [main] INFO  cfig.bootimg.cpio.AndroidCpio - loading build/unzip_boot/ramdisk.img_filelist.txt
22:28:08.505 [main] INFO  ZipHelper - compress(gz) done: build/unzip_boot/ramdisk.img.gz
22:28:08.505 [main] INFO  cfig.bootimg.Common - build/unzip_boot/ramdisk.img.gz is ready
22:28:08.508 [main] WARN  cfig.bootimg.v2.BootV2 - using fake recoveryDtboOffset 41811968 (as is in AOSP avbtool)
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at cfig.packable.PackableLauncherKt.main(PackableLauncher.kt:108)
Caused by: java.lang.IllegalArgumentException: invalid os_version
        at cfig.bootimg.Common$Companion.packOsVersion(Common.kt:74)
        at cfig.bootimg.v2.BootHeaderV2.encode(BootHeaderV2.kt:125)
        at cfig.bootimg.v2.BootV2.pack(BootV2.kt:416)
        at cfig.packable.BootImgParser.pack(BootImgParser.kt:86)
        ... 8 more

> Task :pack FAILED

FAILURE: Build failed with an exception.

```

HI guys im using this: https://github.com/pjgowtham/recovery_device_oplus_nicky.git and it compile on android 12 but M.T.P. dont mount i enable too in twrp and still no m.t.p. so i unpack recoveryimage to see what is wrong and try remove some same links. After repack it comment error:

**Comment by cfig** [comment]
Hi @bgman111111 ,
Can you upload your "recovery.img", if it's not confidential?
I checked "recovery_device_oplus_nicky" and it seems to be a huge repo.

**Comment by bgman111111** [comment]
Hi thank for reply. This can be closed. As it was kernel source culprit. But I have TWRP 12 recovery image and didn't test it, what I, remember is maybe too it didn't work. This happens on Android 12 only.

**Comment by cfig** [comment]
OK~
